stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm i
  artifacts:
    untracked: true
    expire_in: '30 mins'
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - 'dist'
    expire_in: '30 mins'
  dependencies:
    - install

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt-get -y update
    - apt install git build-essential autoconf dh-autoreconf libcurl4-openssl-dev \
      tcl-dev gettext asciidoc docbook2x install-info \
      libexpat1-dev libz-dev -y
    - mkdir forPushToGithub
    - cd forPushToGithub
    - git init
    - git remote add origin 'https://$GITHUB_TOKEN@github.com/Loloao/my-blog.git'
    - git config --global http.version HTTP/1.1
    - git pull
    - git switch master
    - rm -r *
    - mv ../dist/* .
    - git add .
    - "git commit -m ':arrow_up: update blog resource'"
    - 'git push'
