stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm i
    - npm run test

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "deploy it!!"
