stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm i
  artifacts:
    untracked: true
    expire_in: '30 mins'
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - 'dist'
    expire_in: '30 mins'
  dependencies:
    - install

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install

deploy:
  stage: deploy
  script:
    - echo "deploy it!!"
